"""add profile_picture_url to competitor_accounts

Revision ID: 0b5d73cbc460
Revises: e78674adcf4d
Create Date: 2026-06-13 12:10:30.124128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b5d73cbc460'
down_revision: Union[str, Sequence[str], None] = 'e78674adcf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_accounts', sa.Column('profile_picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor_accounts', 'profile_picture_url')
    # ### end Alembic commands ###
